### PR TITLE
Aj/exploration

### PR DESCRIPTION
**Pull request by ajohn104**
Restructures assets, cleans up code, improves on controller support, adds basic multiplayer support

### CODE REVIEW

**Comment by mcoccia** [comment]
It looks good to me!

**Comment by akrs** [comment]
:-1: 

Seems to have broken keyboard and mouse input. We should try rebuilding these changes without multiplayer, and also do major work on the input library

**Comment by ajohn104** [comment]
Multiplayer was completely removed in the last commit, and both mouse and keyboard input are fine on my end. Keyboard is always enabled, but I do have it set to where mouse input is ignored if a controller is plugged in. Are you sure you're on the latest build?

As a matter of fact, not that it should make a difference, are you experiencing the issue in the editor or the standalone?

**Comment by mcoccia** [comment]
On second check (I didnt mess up this time) I can't get it to work on my computer now

**Comment by ajohn104** [comment]
Well, then that worries me. It's definitely working on my end. I'll look into it in the morning, but there's not much I can do since its working for me. Anything coming from the console when it doesn't work? Or just silence?

**Comment by mcoccia** [comment]
Note. Need to have VR off (in Edit -> Project Settings -> Player -> PC, Mac, & Standalone Settings -> VR supported) in order to not crash on mac.

**Comment by akrs** [comment]
Looks good to me.

**Pull request merged**
